"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "hi" | "bn" | "ta" | "te" | "mr" | "gu";

export const languages: { code: Language; name: string; nativeName: string }[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
];

// Translations
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    home: "Home",
    aiDetection: "AI Detection",
    opdBooking: "OPD Booking",
    ambulance: "Ambulance",
    hospitals: "Hospitals",
    doctors: "Doctors",
    pharmacy: "Pharmacy",
    
    // Hero Section
    aiPoweredHealthcare: "AI-Powered Healthcare",
    yourComplete: "Your Complete",
    healthcareCompanion: "Healthcare Companion",
    heroDescription: "Experience the future of healthcare with AI-powered disease detection, seamless OPD booking, real-time ambulance tracking, and more — all in one platform.",
    tryAIDiagnosis: "Try AI Diagnosis",
    bookAppointment: "Book Appointment",
    hipaaCompliant: "HIPAA Compliant",
    yourDataSecure: "Your data is secure",
    available247: "24/7 Available",
    alwaysHere: "Always here",
    aiAccuracy: "95% Accuracy",
    aiDetectionLabel: "AI Detection",
    patients: "Patients",
    doctorsLabel: "Doctors",
    
    // Services
    ourServices: "Our Services",
    servicesDescription: "Comprehensive healthcare solutions designed to make your medical journey seamless and efficient.",
    aiDiseaseDetection: "AI Disease Detection",
    aiDiseaseDesc: "Get instant AI-powered analysis of your symptoms with high accuracy diagnostics.",
    opdBookingTitle: "OPD Booking",
    opdBookingDesc: "Book outpatient appointments with top doctors in just a few clicks.",
    ambulanceTracking: "Ambulance Tracking",
    ambulanceDesc: "Track ambulances in real-time and request emergency services instantly.",
    nearbyHospitals: "Nearby Hospitals",
    hospitalsDesc: "Find hospitals near you with real-time availability and directions.",
    doctorProfiles: "Doctor Profiles",
    doctorsDesc: "Browse detailed profiles of qualified doctors across specializations.",
    medicalShops: "Medical Shops",
    pharmacyDesc: "Locate pharmacies near you with medicine availability and pricing.",
    patientDischarge: "Patient Discharge",
    patientDischargeDesc: "Manage and track the complete patient discharge process efficiently.",
    
    // Stats
    patientsServed: "Patients Served",
    expertDoctors: "Expert Doctors",
    partnerHospitals: "Partner Hospitals",
    
    // Footer
    footerTagline: "Your trusted healthcare companion for AI-powered diagnostics and seamless medical services.",
    services: "Services",
    quickLinks: "Quick Links",
    findHospitals: "Find Hospitals",
    ourDoctors: "Our Doctors",
    aboutUs: "About Us",
    contact: "Contact",
    allRightsReserved: "All rights reserved.",
    
    // Rural Features
    offlineAvailable: "Works Offline",
    lowDataMode: "Low Data Mode",
    voiceSupport: "Voice Support",
    tollFreeNumber: "Toll Free: 1800-XXX-XXXX",
    emergencyHelpline: "Emergency Helpline",
    callNow: "Call Now",
    smsService: "SMS Service",
    sendSMS: "Send SMS",
    nearestCenter: "Nearest Health Center",
    kmAway: "km away",
    ruralHealthFeatures: "Rural Health Features",
    ruralDescription: "Special features designed for rural communities with limited connectivity.",
    teleconsultation: "Teleconsultation",
    teleconsultDesc: "Connect with doctors via video or voice call",
    healthWorkerConnect: "Health Worker Connect",
    healthWorkerDesc: "Connect with ASHA workers in your area",
    mobileClinic: "Mobile Clinic",
    mobileClinicDesc: "Check mobile clinic schedules in your village",
    medicineDroneDelivery: "Medicine Drone Delivery",
    droneDeliveryDesc: "Get medicines delivered by drone to remote areas",
    
    // AI Detection Page
    symptomChecker: "AI Symptom Checker",
    symptomCheckerDesc: "Describe your symptoms and get AI-powered health insights",
    selectSymptoms: "Select Your Symptoms",
    selectedSymptoms: "Selected Symptoms",
    analyzeSymptoms: "Analyze Symptoms",
    analyzing: "Analyzing...",
    clearAll: "Clear All",
    analysisResults: "Analysis Results",
    possibleConditions: "Possible Conditions",
    confidence: "Confidence",
    severity: "Severity",
    recommendations: "Recommendations",
    consultDoctor: "Consult a Doctor",
    bookNow: "Book Now",
    disclaimer: "Disclaimer",
    disclaimerText: "This AI analysis is for informational purposes only and should not replace professional medical advice. Please consult a healthcare provider for accurate diagnosis and treatment.",
    
    // Common
    search: "Search",
    filter: "Filter",
    apply: "Apply",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    loading: "Loading...",
    noResults: "No results found",
    viewAll: "View All",
    learnMore: "Learn More",
    getStarted: "Get Started",
    
    // OPD Booking
    selectDepartment: "Select Department",
    selectDoctor: "Select Doctor",
    selectDateTime: "Select Date & Time",
    confirmBooking: "Confirm Booking",
    appointmentBooked: "Appointment Booked",
    appointmentDetails: "Appointment Details",
    
    // Ambulance
    requestAmbulance: "Request Ambulance",
    emergencyType: "Emergency Type",
    location: "Location",
    patientDetails: "Patient Details",
    trackAmbulance: "Track Ambulance",
    eta: "ETA",
    driverContact: "Driver Contact",
    
    // Hospitals
    searchHospitals: "Search Hospitals",
    bedsAvailable: "Beds Available",
    icuBeds: "ICU Beds",
    emergencyServices: "Emergency Services",
    departments: "Departments",
    
    // Doctors
    searchDoctors: "Search Doctors",
    specialization: "Specialization",
    experience: "Experience",
    consultationFee: "Consultation Fee",
    rating: "Rating",
    
    // Pharmacy
    searchMedicine: "Search Medicine",
    pharmacyNearYou: "Pharmacies Near You",
    medicineAvailable: "Medicine Available",
    delivery: "Delivery",
    openNow: "Open Now",
    
    // Theme
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemTheme: "System",
    
    // Language
    selectLanguage: "Select Language",
    language: "Language",
  },
  hi: {
    // Navigation
    home: "होम",
    aiDetection: "AI जांच",
    opdBooking: "OPD बुकिंग",
    ambulance: "एम्बुलेंस",
    hospitals: "अस्पताल",
    doctors: "डॉक्टर",
    pharmacy: "दवाखाना",
    
    // Hero Section
    aiPoweredHealthcare: "AI-संचालित स्वास्थ्य सेवा",
    yourComplete: "आपका संपूर्ण",
    healthcareCompanion: "स्वास्थ्य साथी",
    heroDescription: "AI-संचालित रोग पहचान, आसान OPD बुकिंग, रीयल-टाइम एम्बुलेंस ट्रैकिंग और बहुत कुछ - सब एक प्लेटफॉर्म पर।",
    tryAIDiagnosis: "AI जांच करें",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    hipaaCompliant: "HIPAA अनुपालित",
    yourDataSecure: "आपका डेटा सुरक्षित",
    available247: "24/7 उपलब्ध",
    alwaysHere: "हमेशा यहां",
    aiAccuracy: "95% सटीकता",
    aiDetectionLabel: "AI जांच",
    patients: "मरीज",
    doctorsLabel: "डॉक्टर",
    
    // Services
    ourServices: "हमारी सेवाएं",
    servicesDescription: "आपकी चिकित्सा यात्रा को आसान बनाने के लिए व्यापक स्वास्थ्य समाधान।",
    aiDiseaseDetection: "AI रोग पहचान",
    aiDiseaseDesc: "अपने लक्षणों का त्वरित AI-संचालित विश्लेषण प्राप्त करें।",
    opdBookingTitle: "OPD बुकिंग",
    opdBookingDesc: "कुछ क्लिक में शीर्ष डॉक्टरों के साथ अपॉइंटमेंट बुक करें।",
    ambulanceTracking: "एम्बुलेंस ट्रैकिंग",
    ambulanceDesc: "रीयल-टाइम में एम्बुलेंस ट्रैक करें और आपातकालीन सेवाओं का अनुरोध करें।",
    nearbyHospitals: "नजदीकी अस्पताल",
    hospitalsDesc: "अपने पास अस्पताल खोजें और दिशा-निर्देश प्राप्त करें।",
    doctorProfiles: "डॉक्टर प्रोफाइल",
    doctorsDesc: "विभिन्न विशेषज्ञताओं में योग्य डॉक्टरों की प्रोफाइल देखें।",
    medicalShops: "मेडिकल दुकानें",
    pharmacyDesc: "अपने पास दवाखाने खोजें और दवाओं की उपलब्धता जांचें।",
    patientDischarge: "मरीज डिस्चार्ज",
    patientDischargeDesc: "मरीज की छुट्टी की पूरी प्रक्रिया को कुशलतापूर्वक प्रबंधित और ट्रैक करें।",
    
    // Stats
    patientsServed: "मरीजों की सेवा",
    expertDoctors: "विशेषज्ञ डॉक्टर",
    partnerHospitals: "पार्टनर अस्पताल",
    
    // Footer
    footerTagline: "AI-संचालित निदान और सुगम चिकित्सा सेवाओं के लिए आपका विश्वसनीय स्वास्थ्य साथी।",
    services: "सेवाएं",
    quickLinks: "त्वरित लिंक",
    findHospitals: "अस्पताल खोजें",
    ourDoctors: "हमारे डॉक्टर",
    aboutUs: "हमारे बारे में",
    contact: "संपर्क",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    
    // Rural Features
    offlineAvailable: "ऑफलाइन उपलब्ध",
    lowDataMode: "कम डेटा मोड",
    voiceSupport: "आवाज सहायता",
    tollFreeNumber: "टोल फ्री: 1800-XXX-XXXX",
    emergencyHelpline: "आपातकालीन हेल्पलाइन",
    callNow: "अभी कॉल करें",
    smsService: "SMS सेवा",
    sendSMS: "SMS भेजें",
    nearestCenter: "निकटतम स्वास्थ्य केंद्र",
    kmAway: "किमी दूर",
    ruralHealthFeatures: "ग्रामीण स्वास्थ्य सुविधाएं",
    ruralDescription: "सीमित कनेक्टिविटी वाले ग्रामीण समुदायों के लिए विशेष सुविधाएं।",
    teleconsultation: "टेलीकंसल्टेशन",
    teleconsultDesc: "वीडियो या वॉयस कॉल से डॉक्टर से जुड़ें",
    healthWorkerConnect: "स्वास्थ्य कार्यकर्ता संपर्क",
    healthWorkerDesc: "अपने क्षेत्र में आशा कार्यकर्ताओं से जुड़ें",
    mobileClinic: "मोबाइल क्लिनिक",
    mobileClinicDesc: "अपने गांव में मोबाइल क्लिनिक की अनुसूची देखें",
    medicineDroneDelivery: "ड्रोन दवा डिलीवरी",
    droneDeliveryDesc: "दूरदराज के क्षेत्रों में ड्रोन से दवाएं प्राप्त करें",
    
    // AI Detection Page
    symptomChecker: "AI लक्षण जांचकर्ता",
    symptomCheckerDesc: "अपने लक्षण बताएं और AI-संचालित स्वास्थ्य जानकारी प्राप्त करें",
    selectSymptoms: "अपने लक्षण चुनें",
    selectedSymptoms: "चुने गए लक्षण",
    analyzeSymptoms: "लक्षणों का विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    clearAll: "सब साफ करें",
    analysisResults: "विश्लेषण परिणाम",
    possibleConditions: "संभावित स्थितियां",
    confidence: "विश्वास",
    severity: "गंभीरता",
    recommendations: "सिफारिशें",
    consultDoctor: "डॉक्टर से परामर्श लें",
    bookNow: "अभी बुक करें",
    disclaimer: "अस्वीकरण",
    disclaimerText: "यह AI विश्लेषण केवल जानकारी के लिए है और पेशेवर चिकित्सा सलाह की जगह नहीं ले सकता। सटीक निदान के लिए कृपया डॉक्टर से परामर्श लें।",
    
    // Common
    search: "खोजें",
    filter: "फ़िल्टर",
    apply: "लागू करें",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    back: "वापस",
    next: "आगे",
    loading: "लोड हो रहा है...",
    noResults: "कोई परिणाम नहीं मिला",
    viewAll: "सभी देखें",
    learnMore: "और जानें",
    getStarted: "शुरू करें",
    
    // OPD Booking
    selectDepartment: "विभाग चुनें",
    selectDoctor: "डॉक्टर चुनें",
    selectDateTime: "दिनांक और समय चुनें",
    confirmBooking: "बुकिंग की पुष्टि करें",
    appointmentBooked: "अपॉइंटमेंट बुक हो गई",
    appointmentDetails: "अपॉइंटमेंट विवरण",
    
    // Ambulance
    requestAmbulance: "एम्बुलेंस का अनुरोध करें",
    emergencyType: "आपातकाल का प्रकार",
    location: "स्थान",
    patientDetails: "मरीज विवरण",
    trackAmbulance: "एम्बुलेंस ट्रैक करें",
    eta: "पहुंचने का समय",
    driverContact: "ड्राइवर संपर्क",
    
    // Hospitals
    searchHospitals: "अस्पताल खोजें",
    bedsAvailable: "बेड उपलब्ध",
    icuBeds: "ICU बेड",
    emergencyServices: "आपातकालीन सेवाएं",
    departments: "विभाग",
    
    // Doctors
    searchDoctors: "डॉक्टर खोजें",
    specialization: "विशेषज्ञता",
    experience: "अनुभव",
    consultationFee: "परामर्श शुल्क",
    rating: "रेटिंग",
    
    // Pharmacy
    searchMedicine: "दवा खोजें",
    pharmacyNearYou: "आपके पास दवाखाने",
    medicineAvailable: "दवा उपलब्ध",
    delivery: "डिलीवरी",
    openNow: "अभी खुला",
    
    // Theme
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemTheme: "सिस्टम",
    
    // Language
    selectLanguage: "भाषा चुनें",
    language: "भाषा",
  },
  bn: {
    // Navigation
    home: "হোম",
    aiDetection: "AI সনাক্তকরণ",
    opdBooking: "OPD বুকিং",
    ambulance: "অ্যাম্বুলেন্স",
    hospitals: "হাসপাতাল",
    doctors: "ডাক্তার",
    pharmacy: "ফার্মেসি",
    
    // Hero Section
    aiPoweredHealthcare: "AI-চালিত স্বাস্থ্যসেবা",
    yourComplete: "আপনার সম্পূর্ণ",
    healthcareCompanion: "স্বাস্থ্য সঙ্গী",
    heroDescription: "AI-চালিত রোগ সনাক্তকরণ, সহজ OPD বুকিং, রিয়েল-টাইম অ্যাম্বুলেন্স ট্র্যাকিং এবং আরও অনেক কিছু - সব এক প্ল্যাটফর্মে।",
    tryAIDiagnosis: "AI রোগনির্ণয় চেষ্টা করুন",
    bookAppointment: "অ্যাপয়েন্টমেন্ট বুক করুন",
    hipaaCompliant: "HIPAA অনুসারী",
    yourDataSecure: "আপনার ডেটা সুরক্ষিত",
    available247: "২৪/৭ উপলব্ধ",
    alwaysHere: "সর্বদা এখানে",
    aiAccuracy: "৯৫% নির্ভুলতা",
    aiDetectionLabel: "AI সনাক্তকরণ",
    patients: "রোগী",
    doctorsLabel: "ডাক্তার",
    
    // Services
    ourServices: "আমাদের সেবা",
    servicesDescription: "আপনার চিকিৎসা যাত্রা সহজ করতে ব্যাপক স্বাস্থ্য সমাধান।",
    aiDiseaseDetection: "AI রোগ সনাক্তকরণ",
    aiDiseaseDesc: "আপনার লক্ষণগুলির তাত্ক্ষণিক AI-চালিত বিশ্লেষণ পান।",
    opdBookingTitle: "OPD বুকিং",
    opdBookingDesc: "কয়েক ক্লিকে শীর্ষ ডাক্তারদের সাথে অ্যাপয়েন্টমেন্ট বুক করুন।",
    ambulanceTracking: "অ্যাম্বুলেন্স ট্র্যাকিং",
    ambulanceDesc: "রিয়েল-টাইমে অ্যাম্বুলেন্স ট্র্যাক করুন এবং জরুরি সেবার অনুরোধ করুন।",
    nearbyHospitals: "কাছের হাসপাতাল",
    hospitalsDesc: "আপনার কাছে হাসপাতাল খুঁজুন এবং দিকনির্দেশ পান।",
    doctorProfiles: "ডাক্তার প্রোফাইল",
    doctorsDesc: "বিভিন্ন বিশেষজ্ঞতায় যোগ্য ডাক্তারদের প্রোফাইল দেখুন।",
    medicalShops: "মেডিকেল দোকান",
    patientDischarge: "রোগী ডিসচার্জ",
    patientDischargeDesc: "রোগীর ডিসচার্জের সম্পূর্ণ প্রক্রিয়াটি দক্ষতার સાથે পরিচালনা এবং ট্র্যাক করুন।",
    pharmacyDesc: "আপনার কাছে ফার্মেসি খুঁজুন এবং ওষুধের প্রাপ্যতা পরীক্ষা করুন।",
    
    // Stats
    patientsServed: "রোগীদের সেবা",
    expertDoctors: "বিশেষজ্ঞ ডাক্তার",
    partnerHospitals: "অংশীদার হাসপাতাল",
    
    // Footer
    footerTagline: "AI-চালিত রোগনির্ণয় এবং নিরবচ্ছিন্ন চিকিৎসা সেবার জন্য আপনার বিশ্বস্ত স্বাস্থ্য সঙ্গী।",
    services: "সেবা",
    quickLinks: "দ্রুত লিঙ্ক",
    findHospitals: "হাসপাতাল খুঁজুন",
    ourDoctors: "আমাদের ডাক্তার",
    aboutUs: "আমাদের সম্পর্কে",
    contact: "যোগাযোগ",
    allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।",
    
    // Rural Features
    offlineAvailable: "অফলাইনে উপলব্ধ",
    lowDataMode: "কম ডেটা মোড",
    voiceSupport: "ভয়েস সাপোর্ট",
    tollFreeNumber: "টোল ফ্রি: ১৮০০-XXX-XXXX",
    emergencyHelpline: "জরুরি হেল্পলাইন",
    callNow: "এখনই কল করুন",
    smsService: "SMS সেবা",
    sendSMS: "SMS পাঠান",
    nearestCenter: "নিকটতম স্বাস্থ্য কেন্দ্র",
    kmAway: "কিমি দূরে",
    ruralHealthFeatures: "গ্রামীণ স্বাস্থ্য সুবিধা",
    ruralDescription: "সীমিত সংযোগের গ্রামীণ সম্প্রদায়ের জন্য বিশেষ সুবিধা।",
    teleconsultation: "টেলিকনসালটেশন",
    teleconsultDesc: "ভিডিও বা ভয়েস কলে ডাক্তারের সাথে সংযুক্ত হন",
    healthWorkerConnect: "স্বাস্থ্য কর্মী সংযোগ",
    healthWorkerDesc: "আপনার এলাকায় আশা কর্মীদের সাথে সংযুক্ত হন",
    mobileClinic: "মোবাইল ক্লিনিক",
    mobileClinicDesc: "আপনার গ্রামে মোবাইল ক্লিনিকের সময়সূচী দেখুন",
    medicineDroneDelivery: "ড্রোন ওষুধ ডেলিভারি",
    droneDeliveryDesc: "প্রত্যন্ত অঞ্চলে ড্রোন দিয়ে ওষুধ পান",
    
    // AI Detection Page
    symptomChecker: "AI লক্ষণ পরীক্ষক",
    symptomCheckerDesc: "আপনার লক্ষণ বর্ণনা করুন এবং AI-চালিত স্বাস্থ্য তথ্য পান",
    selectSymptoms: "আপনার লক্ষণ নির্বাচন করুন",
    selectedSymptoms: "নির্বাচিত লক্ষণ",
    analyzeSymptoms: "লক্ষণ বিশ্লেষণ করুন",
    analyzing: "বিশ্লেষণ হচ্ছে...",
    clearAll: "সব মুছুন",
    analysisResults: "বিশ্লেষণ ফলাফল",
    possibleConditions: "সম্ভাব্য অবস্থা",
    confidence: "আস্থা",
    severity: "তীব্রতা",
    recommendations: "সুপারিশ",
    consultDoctor: "ডাক্তারের পরামর্শ নিন",
    bookNow: "এখনই বুক করুন",
    disclaimer: "দাবিত্যাগ",
    disclaimerText: "এই AI বিশ্লেষণ শুধুমাত্র তথ্যের জন্য এবং পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়। সঠিক রোগনির্ণয়ের জন্য অনুগ্রহ করে ডাক্তারের পরামর্শ নিন।",
    
    // Common
    search: "খুঁজুন",
    filter: "ফিল্টার",
    apply: "প্রয়োগ করুন",
    cancel: "বাতিল",
    confirm: "নিশ্চিত করুন",
    back: "পিছনে",
    next: "পরবর্তী",
    loading: "লোড হচ্ছে...",
    noResults: "কোন ফলাফল পাওয়া যায়নি",
    viewAll: "সব দেখুন",
    learnMore: "আরও জানুন",
    getStarted: "শুরু করুন",
    
    // OPD Booking
    selectDepartment: "বিভাগ নির্বাচন করুন",
    selectDoctor: "ডাক্তার নির্বাচন করুন",
    selectDateTime: "তারিখ ও সময় নির্বাচন করুন",
    confirmBooking: "বুকিং নিশ্চিত করুন",
    appointmentBooked: "অ্যাপয়েন্টমেন্ট বুক হয়েছে",
    appointmentDetails: "অ্যাপয়েন্টমেন্ট বিবরণ",
    
    // Ambulance
    requestAmbulance: "অ্যাম্বুলেন্স অনুরোধ করুন",
    emergencyType: "জরুরি অবস্থার ধরন",
    location: "অবস্থান",
    patientDetails: "রোগীর বিবরণ",
    trackAmbulance: "অ্যাম্বুলেন্স ট্র্যাক করুন",
    eta: "পৌঁছানোর সময়",
    driverContact: "ড্রাইভার যোগাযোগ",
    
    // Hospitals
    searchHospitals: "হাসপাতাল খুঁজুন",
    bedsAvailable: "বেড উপলব্ধ",
    icuBeds: "ICU বেড",
    emergencyServices: "জরুরি সেবা",
    departments: "বিভাগ",
    
    // Doctors
    searchDoctors: "ডাক্তার খুঁজুন",
    specialization: "বিশেষজ্ঞতা",
    experience: "অভিজ্ঞতা",
    consultationFee: "পরামর্শ ফি",
    rating: "রেটিং",
    
    // Pharmacy
    searchMedicine: "ওষুধ খুঁজুন",
    pharmacyNearYou: "আপনার কাছে ফার্মেসি",
    medicineAvailable: "ওষুধ উপলব্ধ",
    delivery: "ডেলিভারি",
    openNow: "এখন খোলা",
    
    // Theme
    lightMode: "লাইট মোড",
    darkMode: "ডার্ক মোড",
    systemTheme: "সিস্টেম",
    
    // Language
    selectLanguage: "ভাষা নির্বাচন করুন",
    language: "ভাষা",
  },
  ta: {
    home: "முகப்பு",
    aiDetection: "AI கண்டறிதல்",
    opdBooking: "OPD முன்பதிவு",
    ambulance: "ஆம்புலன்ஸ்",
    hospitals: "மருத்துவமனைகள்",
    doctors: "மருத்துவர்கள்",
    pharmacy: "மருந்தகம்",
    aiPoweredHealthcare: "AI-இயக்கப்பட்ட சுகாதாரம்",
    yourComplete: "உங்கள் முழுமையான",
    healthcareCompanion: "சுகாதார துணை",
    heroDescription: "AI-இயக்கப்பட்ட நோய் கண்டறிதல், எளிய OPD முன்பதிவு, நேரடி ஆம்புலன்ஸ் கண்காணிப்பு மற்றும் பல - அனைத்தும் ஒரே தளத்தில்.",
    tryAIDiagnosis: "AI நோயறிதலை முயற்சிக்கவும்",
    bookAppointment: "சந்திப்பு முன்பதிவு",
    hipaaCompliant: "HIPAA இணக்கம்",
    yourDataSecure: "உங்கள் தரவு பாதுகாப்பானது",
    available247: "24/7 கிடைக்கும்",
    alwaysHere: "எப்போதும் இங்கே",
    aiAccuracy: "95% துல்லியம்",
    aiDetectionLabel: "AI கண்டறிதல்",
    patients: "நோயாளிகள்",
    doctorsLabel: "மருத்துவர்கள்",
    ourServices: "எங்கள் சேவைகள்",
    servicesDescription: "உங்கள் மருத்துவ பயணத்தை எளிதாக்க விரிவான சுகாதார தீர்வுகள்.",
    aiDiseaseDetection: "AI நோய் கண்டறிதல்",
    aiDiseaseDesc: "உங்கள் அறிகுறிகளின் உடனடி AI-இயக்கப்பட்ட பகுப்பாய்வு பெறுங்கள்.",
    opdBookingTitle: "OPD முன்பதிவு",
    opdBookingDesc: "சில கிளிக்குகளில் சிறந்த மருத்துவர்களுடன் சந்திப்பை முன்பதிவு செய்யுங்கள்.",
    ambulanceTracking: "ஆம்புலன்ஸ் கண்காணிப்பு",
    ambulanceDesc: "நேரடியாக ஆம்புலன்ஸை கண்காணித்து அவசர சேவைகளை கோருங்கள்.",
    nearbyHospitals: "அருகிலுள்ள மருத்துவமனைகள்",
    hospitalsDesc: "உங்கள் அருகில் மருத்துவமனைகளை கண்டறிந்து திசைகளை பெறுங்கள்.",
    doctorProfiles: "மருத்துவர் சுயவிவரங்கள்",
    doctorsDesc: "பல்வேறு நிபுணத்துவங்களில் தகுதியான மருத்துவர்களின் சுயவிவரங்களை பார்க்கவும்.",
    medicalShops: "மருந்து கடைகள்",
    pharmacyDesc: "உங்கள் அருகில் மருந்தகங்களை கண்டறிந்து மருந்துகளின் கிடைக்கும்நிலையை சரிபார்க்கவும்.",
    patientDischarge: "நோயாளி வெளியேற்றம்",
    patientDischargeDesc: "நோயாளி வெளியேற்ற செயல்முறையை திறமையாக நிர்வகிக்கவும் மற்றும் கண்காணிக்கவும்.",
    patientsServed: "சேவை செய்யப்பட்ட நோயாளிகள்",
    expertDoctors: "நிபுணர் மருத்துவர்கள்",
    partnerHospitals: "கூட்டாளி மருத்துவமனைகள்",
    footerTagline: "AI-இயக்கப்பட்ட நோயறிதல் மற்றும் தடையற்ற மருத்துவ சேவைகளுக்கான உங்கள் நம்பகமான சுகாதார துணை.",
    services: "சேவைகள்",
    quickLinks: "விரைவு இணைப்புகள்",
    findHospitals: "மருத்துவமனைகளை கண்டறி",
    ourDoctors: "எங்கள் மருத்துவர்கள்",
    aboutUs: "எங்களைப் பற்றி",
    contact: "தொடர்பு",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    offlineAvailable: "ஆஃப்லைனில் கிடைக்கும்",
    lowDataMode: "குறைந்த தரவு பயன்முறை",
    voiceSupport: "குரல் ஆதரவு",
    tollFreeNumber: "டோல் ஃப்ரீ: 1800-XXX-XXXX",
    emergencyHelpline: "அவசர உதவி எண்",
    callNow: "இப்போது அழைக்கவும்",
    smsService: "SMS சேவை",
    sendSMS: "SMS அனுப்பு",
    nearestCenter: "அருகிலுள்ள சுகாதார நிலையம்",
    kmAway: "கிமீ தொலைவில்",
    ruralHealthFeatures: "கிராமப்புற சுகாதார அம்சங்கள்",
    ruralDescription: "குறைந்த இணைப்புள்ள கிராமப்புற சமூகங்களுக்கான சிறப்பு அம்சங்கள்.",
    teleconsultation: "தொலை ஆலோசனை",
    teleconsultDesc: "வீடியோ அல்லது குரல் அழைப்பு மூலம் மருத்துவர்களுடன் இணையுங்கள்",
    healthWorkerConnect: "சுகாதார பணியாளர் இணைப்பு",
    healthWorkerDesc: "உங்கள் பகுதியில் ஆஷா பணியாளர்களுடன் இணையுங்கள்",
    mobileClinic: "நடமாடும் மருத்துவமனை",
    mobileClinicDesc: "உங்கள் கிராமத்தில் நடமாடும் மருத்துவமனை அட்டவணையை பார்க்கவும்",
    medicineDroneDelivery: "ட்ரோன் மருந்து விநியோகம்",
    droneDeliveryDesc: "தொலைதூர பகுதிகளுக்கு ட்ரோன் மூலம் மருந்துகளை பெறுங்கள்",
    symptomChecker: "AI அறிகுறி சரிபார்ப்பு",
    symptomCheckerDesc: "உங்கள் அறிகுறிகளை விவரிக்கவும் மற்றும் AI-இயக்கப்பட்ட சுகாதார தகவல்களை பெறவும்",
    selectSymptoms: "உங்கள் அறிகுறிகளை தேர்ந்தெடுக்கவும்",
    selectedSymptoms: "தேர்ந்தெடுக்கப்பட்ட அறிகுறிகள்",
    analyzeSymptoms: "அறிகுறிகளை பகுப்பாய்வு செய்",
    analyzing: "பகுப்பாய்வு செய்யப்படுகிறது...",
    clearAll: "அனைத்தையும் அழி",
    analysisResults: "பகுப்பாய்வு முடிவுகள்",
    possibleConditions: "சாத்தியமான நிலைகள்",
    confidence: "நம்பிக்கை",
    severity: "தீவிரம்",
    recommendations: "பரிந்துரைகள்",
    consultDoctor: "மருத்துவரை அணுகவும்",
    bookNow: "இப்போது முன்பதிவு செய்",
    disclaimer: "மறுப்பு",
    disclaimerText: "இந்த AI பகுப்பாய்வு தகவல் நோக்கங்களுக்கு மட்டுமே மற்றும் தொழில்முறை மருத்துவ ஆலோசனையை மாற்றாது. துல்லியமான நோயறிதலுக்கு மருத்துவரை அணுகவும்.",
    search: "தேடு",
    filter: "வடிகட்டி",
    apply: "பயன்படுத்து",
    cancel: "ரத்து செய்",
    confirm: "உறுதிப்படுத்து",
    back: "பின்",
    next: "அடுத்து",
    loading: "ஏற்றுகிறது...",
    noResults: "முடிவுகள் கிடைக்கவில்லை",
    viewAll: "அனைத்தையும் காண்",
    learnMore: "மேலும் அறிய",
    getStarted: "தொடங்கு",
    selectDepartment: "துறையை தேர்ந்தெடு",
    selectDoctor: "மருத்துவரை தேர்ந்தெடு",
    selectDateTime: "தேதி மற்றும் நேரத்தை தேர்ந்தெடு",
    confirmBooking: "முன்பதிவை உறுதிப்படுத்து",
    appointmentBooked: "சந்திப்பு முன்பதிவு செய்யப்பட்டது",
    appointmentDetails: "சந்திப்பு விவரங்கள்",
    requestAmbulance: "ஆம்புலன்ஸ் கோரு",
    emergencyType: "அவசர வகை",
    location: "இடம்",
    patientDetails: "நோயாளி விவரங்கள்",
    trackAmbulance: "ஆம்புலன்ஸை கண்காணி",
    eta: "வருகை நேரம்",
    driverContact: "ஓட்டுநர் தொடர்பு",
    searchHospitals: "மருத்துவமனைகளை தேடு",
    bedsAvailable: "படுக்கைகள் கிடைக்கும்",
    icuBeds: "ICU படுக்கைகள்",
    emergencyServices: "அவசர சேவைகள்",
    departments: "துறைகள்",
    searchDoctors: "மருத்துவர்களை தேடு",
    specialization: "நிபுணத்துவம்",
    experience: "அனுபவம்",
    consultationFee: "ஆலோசனை கட்டணம்",
    rating: "மதிப்பீடு",
    searchMedicine: "மருந்து தேடு",
    pharmacyNearYou: "உங்கள் அருகில் மருந்தகங்கள்",
    medicineAvailable: "மருந்து கிடைக்கும்",
    delivery: "விநியோகம்",
    openNow: "இப்போது திறந்திருக்கிறது",
    lightMode: "லைட் பயன்முறை",
    darkMode: "டார்க் பயன்முறை",
    systemTheme: "சிஸ்டம்",
    selectLanguage: "மொழியை தேர்ந்தெடு",
    language: "மொழி",
  },
  te: {
    home: "హోమ్",
    aiDetection: "AI గుర్తింపు",
    opdBooking: "OPD బుకింగ్",
    ambulance: "అంబులెన్స్",
    hospitals: "ఆసుపత్రులు",
    doctors: "వైద్యులు",
    pharmacy: "ఫార్మసీ",
    aiPoweredHealthcare: "AI-ఆధారిత ఆరోగ్య సంరక్షణ",
    yourComplete: "మీ పూర్తి",
    healthcareCompanion: "ఆరోగ్య సహచరుడు",
    heroDescription: "AI-ఆధారిత వ్యాధి గుర్తింపు, సులభమైన OPD బుకింగ్, రియల్-టైమ్ అంబులెన్స్ ట్రాకింగ్ మరియు మరిన్ని - అన్నీ ఒకే ప్లాట్‌ఫామ్‌లో.",
    tryAIDiagnosis: "AI రోగనిర్ధారణ ప్రయత్నించండి",
    bookAppointment: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    hipaaCompliant: "HIPAA అనుకూలం",
    yourDataSecure: "మీ డేటా సురక్షితం",
    available247: "24/7 అందుబాటులో",
    alwaysHere: "ఎల్లప్పుడూ ఇక్కడ",
    aiAccuracy: "95% ఖచ్చితత్వం",
    aiDetectionLabel: "AI గుర్తింపు",
    patients: "రోగులు",
    doctorsLabel: "వైద్యులు",
    ourServices: "మా సేవలు",
    servicesDescription: "మీ వైద్య ప్రయాణాన్ని సులభతరం చేయడానికి సమగ్ర ఆరోగ్య పరిష్కారాలు.",
    aiDiseaseDetection: "AI వ్యాధి గుర్తింపు",
    aiDiseaseDesc: "మీ లక్షణాల తక్షణ AI-ఆధారిత విశ్లేషణ పొందండి.",
    opdBookingTitle: "OPD బుకింగ్",
    opdBookingDesc: "కొన్ని క్లిక్‌లలో టాప్ డాక్టర్లతో అపాయింట్‌మెంట్ బుక్ చేయండి.",
    ambulanceTracking: "అంబులెన్స్ ట్రాకింగ్",
    ambulanceDesc: "రియల్-టైమ్‌లో అంబులెన్స్ ట్రాక్ చేయండి మరియు అత్యవసర సేవలను అభ్యర్థించండి.",
    nearbyHospitals: "సమీపంలోని ఆసుపత్రులు",
    hospitalsDesc: "మీ సమీపంలో ఆసుపత్రులను కనుగొని దిశలు పొందండి.",
    doctorProfiles: "డాక్టర్ ప్రొఫైల్స్",
    doctorsDesc: "వివిధ స్పెషలైజేషన్లలో అర్హత కలిగిన డాక్టర్ల ప్రొఫైల్‌లను చూడండి.",
    medicalShops: "మెడికల్ షాపులు",
    patientDischarge: "రోగి డిశ్చార్జ్",
    patientDischargeDesc: "రోగి డిశ్చార్జ్ ప్రక్రియను సమర్థవంతంగా నిర్వహించండి మరియు ట్రాక్ చేయండి.",
    pharmacyDesc: "మీ సమీపంలో ఫార్మసీలను కనుగొని మందుల లభ్యతను తనిఖీ చేయండి.",
    patientsServed: "సేవలు పొందిన రోగులు",
    expertDoctors: "నిపుణ వైద్యులు",
    partnerHospitals: "భాగస్వామ్య ఆసుపత్రులు",
    footerTagline: "AI-ఆధారిత రోగనిర్ధారణ మరియు అతుకులు లేని వైద్య సేవల కోసం మీ విశ్వసనీయ ఆరోగ్య సహచరుడు.",
    services: "సేవలు",
    quickLinks: "త్వరిత లింక్‌లు",
    findHospitals: "ఆసుపత్రులు కనుగొనండి",
    ourDoctors: "మా డాక్టర్లు",
    aboutUs: "మా గురించి",
    contact: "సంప్రదింపు",
    allRightsReserved: "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.",
    offlineAvailable: "ఆఫ్‌లైన్‌లో అందుబాటులో",
    lowDataMode: "తక్కువ డేటా మోడ్",
    voiceSupport: "వాయిస్ సపోర్ట్",
    tollFreeNumber: "టోల్ ఫ్రీ: 1800-XXX-XXXX",
    emergencyHelpline: "అత్యవసర హెల్ప్‌లైన్",
    callNow: "ఇప్పుడు కాల్ చేయండి",
    smsService: "SMS సేవ",
    sendSMS: "SMS పంపండి",
    nearestCenter: "సమీప ఆరోగ్య కేంద్రం",
    kmAway: "కిమీ దూరంలో",
    ruralHealthFeatures: "గ్రామీణ ఆరోగ్య ఫీచర్లు",
    ruralDescription: "పరిమిత కనెక్టివిటీ ఉన్న గ్రామీణ సమాజాల కోసం ప్రత్యేక ఫీచర్లు.",
    teleconsultation: "టెలికన్సల్టేషన్",
    teleconsultDesc: "వీడియో లేదా వాయిస్ కాల్ ద్వారా డాక్టర్లతో కనెక్ట్ అవ్వండి",
    healthWorkerConnect: "ఆరోగ్య కార్యకర్త కనెక్ట్",
    healthWorkerDesc: "మీ ప్రాంతంలో ఆశా వర్కర్లతో కనెక్ట్ అవ్వండి",
    mobileClinic: "మొబైల్ క్లినిక్",
    mobileClinicDesc: "మీ గ్రామంలో మొబైల్ క్లినిక్ షెడ్యూల్‌లను చూడండి",
    medicineDroneDelivery: "డ్రోన్ మందుల డెలివరీ",
    droneDeliveryDesc: "మారుమూల ప్రాంతాలకు డ్రోన్ ద్వారా మందులు పొందండి",
    symptomChecker: "AI లక్షణ తనిఖీదారు",
    symptomCheckerDesc: "మీ లక్షణాలను వివరించండి మరియు AI-ఆధారిత ఆరోగ్య సమాచారం పొందండి",
    selectSymptoms: "మీ లక్షణాలను ఎంచుకోండి",
    selectedSymptoms: "ఎంచుకున్న లక్షణాలు",
    analyzeSymptoms: "లక్షణాలను విశ్లేషించండి",
    analyzing: "విశ్లేషిస్తోంది...",
    clearAll: "అన్నీ క్లియర్ చేయండి",
    analysisResults: "విశ్లేషణ ఫలితాలు",
    possibleConditions: "సాధ్యమయ్యే పరిస్థితులు",
    confidence: "విశ్వాసం",
    severity: "తీవ్రత",
    recommendations: "సిఫార్సులు",
    consultDoctor: "డాక్టర్‌ను సంప్రదించండి",
    bookNow: "ఇప్పుడు బుక్ చేయండి",
    disclaimer: "నిరాకరణ",
    disclaimerText: "ఈ AI విశ్లేషణ సమాచార ప్రయోజనాల కోసం మాత్రమే మరియు వృత్తిపరమైన వైద్య సలహాను భర్తీ చేయదు. ఖచ్చితమైన రోగనిర్ధారణ కోసం డాక్టర్‌ను సంప్రదించండి.",
    search: "వెతకండి",
    filter: "ఫిల్టర్",
    apply: "అప్లై చేయండి",
    cancel: "రద్దు చేయండి",
    confirm: "నిర్ధారించండి",
    back: "వెనుకకు",
    next: "తదుపరి",
    loading: "లోడ్ అవుతోంది...",
    noResults: "ఫలితాలు కనుగొనబడలేదు",
    viewAll: "అన్నీ చూడండి",
    learnMore: "మరింత తెలుసుకోండి",
    getStarted: "ప్రారంభించండి",
    selectDepartment: "డిపార్ట్‌మెంట్ ఎంచుకోండి",
    selectDoctor: "డాక్టర్‌ను ఎంచుకోండి",
    selectDateTime: "తేదీ మరియు సమయాన్ని ఎంచుకోండి",
    confirmBooking: "బుకింగ్ నిర్ధారించండి",
    appointmentBooked: "అపాయింట్‌మెంట్ బుక్ అయింది",
    appointmentDetails: "అపాయింట్‌మెంట్ వివరాలు",
    requestAmbulance: "అంబులెన్స్ అభ్యర్థించండి",
    emergencyType: "అత్యవసర రకం",
    location: "స్థానం",
    patientDetails: "రోగి వివరాలు",
    trackAmbulance: "అంబులెన్స్ ట్రాక్ చేయండి",
    eta: "చేరుకునే సమయం",
    driverContact: "డ్రైవర్ సంప్రదింపు",
    searchHospitals: "ఆసుపత్రులు వెతకండి",
    bedsAvailable: "బెడ్లు అందుబాటులో",
    icuBeds: "ICU బెడ్లు",
    emergencyServices: "అత్యవసర సేవలు",
    departments: "డిపార్ట్‌మెంట్లు",
    searchDoctors: "డాక్టర్లను వెతకండి",
    specialization: "స్పెషలైజేషన్",
    experience: "అనుభవం",
    consultationFee: "కన్సల్టేషన్ ఫీజు",
    rating: "రేటింగ్",
    searchMedicine: "మందులు వెతకండి",
    pharmacyNearYou: "మీ సమీపంలో ఫార్మసీలు",
    medicineAvailable: "మందులు అందుబాటులో",
    delivery: "డెలివరీ",
    openNow: "ఇప్పుడు తెరిచి ఉంది",
    lightMode: "లైట్ మోడ్",
    darkMode: "డార్క్ మోడ్",
    systemTheme: "సిస్టమ్",
    selectLanguage: "భాషను ఎంచుకోండి",
    language: "భాష",
  },
  mr: {
    home: "मुख्यपृष्ठ",
    aiDetection: "AI शोध",
    opdBooking: "OPD बुकिंग",
    ambulance: "रुग्णवाहिका",
    hospitals: "रुग्णालये",
    doctors: "डॉक्टर",
    pharmacy: "औषधालय",
    aiPoweredHealthcare: "AI-संचालित आरोग्य सेवा",
    yourComplete: "तुमचा संपूर्ण",
    healthcareCompanion: "आरोग्य साथीदार",
    heroDescription: "AI-संचालित रोग शोध, सोपे OPD बुकिंग, रिअल-टाइम रुग्णवाहिका ट्रॅकिंग आणि बरेच काही - सर्व एका प्लॅटफॉर्मवर.",
    tryAIDiagnosis: "AI निदान वापरा",
    bookAppointment: "भेट बुक करा",
    hipaaCompliant: "HIPAA अनुरूप",
    yourDataSecure: "तुमचा डेटा सुरक्षित",
    available247: "24/7 उपलब्ध",
    alwaysHere: "नेहमी येथे",
    aiAccuracy: "95% अचूकता",
    aiDetectionLabel: "AI शोध",
    patients: "रुग्ण",
    doctorsLabel: "डॉक्टर",
    ourServices: "आमच्या सेवा",
    servicesDescription: "तुमचा वैद्यकीय प्रवास सोपा करण्यासाठी व्यापक आरोग्य उपाय.",
    aiDiseaseDetection: "AI रोग शोध",
    aiDiseaseDesc: "तुमच्या लक्षणांचे त्वरित AI-संचालित विश्लेषण मिळवा.",
    opdBookingTitle: "OPD बुकिंग",
    opdBookingDesc: "काही क्लिकमध्ये शीर्ष डॉक्टरांसोबत भेट बुक करा.",
    ambulanceTracking: "रुग्णवाहिका ट्रॅकिंग",
    ambulanceDesc: "रिअल-टाइममध्ये रुग्णवाहिका ट्रॅक करा आणि आणीबाणी सेवांची विनंती करा.",
    nearbyHospitals: "जवळची रुग्णालये",
    hospitalsDesc: "तुमच्या जवळ रुग्णालये शोधा आणि दिशानिर्देश मिळवा.",
    doctorProfiles: "डॉक्टर प्रोफाइल",
    doctorsDesc: "विविध विशेषज्ञतांमध्ये पात्र डॉक्टरांचे प्रोफाइल पहा.",
    medicalShops: "वैद्यकीय दुकाने",
    pharmacyDesc: "तुमच्या जवळ औषधालये शोधा आणि औषधांची उपलब्धता तपासा.",
    patientDischarge: "रुग्ण डिस्चार्ज",
    patientDischargeDesc: "रुग्णाच्या डिस्चार्जची संपूर्ण प्रक्रिया कार्यक्षमतेने व्यवस्थापित करा आणि ट्रॅक करा.",
    patientsServed: "सेवा दिलेले रुग्ण",
    expertDoctors: "तज्ञ डॉक्टर",
    partnerHospitals: "भागीदार रुग्णालये",
    footerTagline: "AI-संचालित निदान आणि अखंड वैद्यकीय सेवांसाठी तुमचा विश्वासार्ह आरोग्य साथीदार.",
    services: "सेवा",
    quickLinks: "जलद दुवे",
    findHospitals: "रुग्णालये शोधा",
    ourDoctors: "आमचे डॉक्टर",
    aboutUs: "आमच्याबद्दल",
    contact: "संपर्क",
    allRightsReserved: "सर्व हक्क राखीव.",
    offlineAvailable: "ऑफलाइन उपलब्ध",
    lowDataMode: "कमी डेटा मोड",
    voiceSupport: "आवाज समर्थन",
    tollFreeNumber: "टोल फ्री: 1800-XXX-XXXX",
    emergencyHelpline: "आणीबाणी हेल्पलाइन",
    callNow: "आता कॉल करा",
    smsService: "SMS सेवा",
    sendSMS: "SMS पाठवा",
    nearestCenter: "जवळचे आरोग्य केंद्र",
    kmAway: "किमी दूर",
    ruralHealthFeatures: "ग्रामीण आरोग्य वैशिष्ट्ये",
    ruralDescription: "मर्यादित कनेक्टिव्हिटी असलेल्या ग्रामीण समुदायांसाठी विशेष वैशिष्ट्ये.",
    teleconsultation: "टेलीकन्सल्टेशन",
    teleconsultDesc: "व्हिडिओ किंवा व्हॉइस कॉलद्वारे डॉक्टरांशी कनेक्ट व्हा",
    healthWorkerConnect: "आरोग्य कार्यकर्ता संपर्क",
    healthWorkerDesc: "तुमच्या भागातील आशा कार्यकर्त्यांशी कनेक्ट व्हा",
    mobileClinic: "मोबाइल क्लिनिक",
    mobileClinicDesc: "तुमच्या गावातील मोबाइल क्लिनिक वेळापत्रक पहा",
    medicineDroneDelivery: "ड्रोन औषध वितरण",
    droneDeliveryDesc: "दुर्गम भागात ड्रोनद्वारे औषधे मिळवा",
    symptomChecker: "AI लक्षण तपासणी",
    symptomCheckerDesc: "तुमची लक्षणे वर्णन करा आणि AI-संचालित आरोग्य माहिती मिळवा",
    selectSymptoms: "तुमची लक्षणे निवडा",
    selectedSymptoms: "निवडलेली लक्षणे",
    analyzeSymptoms: "लक्षणांचे विश्लेषण करा",
    analyzing: "विश्लेषण होत आहे...",
    clearAll: "सर्व साफ करा",
    analysisResults: "विश्लेषण निकाल",
    possibleConditions: "संभाव्य परिस्थिती",
    confidence: "विश्वास",
    severity: "तीव्रता",
    recommendations: "शिफारसी",
    consultDoctor: "डॉक्टरांचा सल्ला घ्या",
    bookNow: "आता बुक करा",
    disclaimer: "अस्वीकरण",
    disclaimerText: "हे AI विश्लेषण केवळ माहितीसाठी आहे आणि व्यावसायिक वैद्यकीय सल्ल्याची जागा घेऊ शकत नाही. अचूक निदानासाठी कृपया डॉक्टरांचा सल्ला घ्या.",
    search: "शोधा",
    filter: "फिल्टर",
    apply: "लागू करा",
    cancel: "रद्द करा",
    confirm: "पुष्टी करा",
    back: "मागे",
    next: "पुढे",
    loading: "लोड होत आहे...",
    noResults: "कोणताही निकाल सापडला नाही",
    viewAll: "सर्व पहा",
    learnMore: "अधिक जाणून घ्या",
    getStarted: "सुरू करा",
    selectDepartment: "विभाग निवडा",
    selectDoctor: "डॉक्टर निवडा",
    selectDateTime: "तारीख आणि वेळ निवडा",
    confirmBooking: "बुकिंगची पुष्टी करा",
    appointmentBooked: "भेट बुक झाली",
    appointmentDetails: "भेटीचे तपशील",
    requestAmbulance: "रुग्णवाहिकेची विनंती करा",
    emergencyType: "आणीबाणीचा प्रकार",
    location: "स्थान",
    patientDetails: "रुग्णाचे तपशील",
    trackAmbulance: "रुग्णवाहिका ट्रॅक करा",
    eta: "पोहोचण्याची वेळ",
    driverContact: "ड्रायव्हर संपर्क",
    searchHospitals: "रुग्णालये शोधा",
    bedsAvailable: "बेड उपलब्ध",
    icuBeds: "ICU बेड",
    emergencyServices: "आणीबाणी सेवा",
    departments: "विभाग",
    searchDoctors: "डॉक्टर शोधा",
    specialization: "विशेषज्ञता",
    experience: "अनुभव",
    consultationFee: "सल्ला शुल्क",
    rating: "रेटिंग",
    searchMedicine: "औषध शोधा",
    pharmacyNearYou: "तुमच्या जवळ औषधालये",
    medicineAvailable: "औषध उपलब्ध",
    delivery: "वितरण",
    openNow: "आता उघडे",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemTheme: "सिस्टम",
    selectLanguage: "भाषा निवडा",
    language: "भाषा",
  },
  gu: {
    home: "હોમ",
    aiDetection: "AI તપાસ",
    opdBooking: "OPD બુકિંગ",
    ambulance: "એમ્બ્યુલન્સ",
    hospitals: "હોસ્પિટલો",
    doctors: "ડોક્ટરો",
    pharmacy: "ફાર્મસી",
    aiPoweredHealthcare: "AI-સંચાલિત આરોગ્ય સંભાળ",
    yourComplete: "તમારો સંપૂર્ણ",
    healthcareCompanion: "આરોગ્ય સાથી",
    heroDescription: "AI-સંચાલિત રોગ શોધ, સરળ OPD બુકિંગ, રીઅલ-ટાઇમ એમ્બ્યુલન્સ ટ્રેકિંગ અને વધુ - બધું એક પ્લેટફોર્મ પર.",
    tryAIDiagnosis: "AI નિદાન અજમાવો",
    bookAppointment: "એપોઇન્ટમેન્ટ બુક કરો",
    hipaaCompliant: "HIPAA અનુરૂપ",
    yourDataSecure: "તમારો ડેટા સુરક્ષિત",
    available247: "24/7 ઉપલબ્ધ",
    alwaysHere: "હંમેશા અહીં",
    aiAccuracy: "95% ચોકસાઈ",
    aiDetectionLabel: "AI તપાસ",
    patients: "દર્દીઓ",
    doctorsLabel: "ડોક્ટરો",
    ourServices: "અમારી સેવાઓ",
    servicesDescription: "તમારી તબીબી યાત્રાને સરળ બનાવવા માટે વ્યાપક આરોગ્ય ઉકેલો.",
    aiDiseaseDetection: "AI રોગ શોધ",
    aiDiseaseDesc: "તમારા લક્ષણોનું ત્વરિત AI-સંચાલિત વિશ્લેષણ મેળવો.",
    opdBookingTitle: "OPD બુકિંગ",
    opdBookingDesc: "થોડા ક્લિકમાં ટોચના ડોક્ટરો સાથે એપોઇન્ટમેન્ટ બુક કરો.",
    ambulanceTracking: "એમ્બ્યુલન્સ ટ્રેકિંગ",
    ambulanceDesc: "રીઅલ-ટાઇમમાં એમ્બ્યુલન્સ ટ્રેક કરો અને કટોકટી સેવાઓની વિનંતી કરો.",
    nearbyHospitals: "નજીકની હોસ્પિટલો",
    hospitalsDesc: "તમારી નજીક હોસ્પિટલો શોધો અને દિશાઓ મેળવો.",
    doctorProfiles: "ડોક્ટર પ્રોફાઇલ",
    doctorsDesc: "વિવિધ વિશેષતાઓમાં લાયક ડોક્ટરોની પ્રોફાઇલ જુઓ.",
    medicalShops: "મેડિકલ દુકાનો",
    pharmacyDesc: "તમારી નજીક ફાર્મસી શોધો અને દવાઓની ઉપલબ્ધતા તપાસો.",
    patientDischarge: "દર્દી ડિસ્ચાર્જ",
    patientDischargeDesc: "દર્દીના ડિસ્ચાર્જની સંપૂર્ણ પ્રક્રિયાને કાર્યક્ષમ રીતે સંચાલિત અને ટ્રેક કરો.",
    patientsServed: "સેવા આપેલ દર્દીઓ",
    expertDoctors: "નિષ્ણાત ડોક્ટરો",
    partnerHospitals: "ભાગીદાર હોસ્પિટલો",
    footerTagline: "AI-સંચાલિત નિદાન અને સીમલેસ તબીબી સેવાઓ માટે તમારો વિશ્વાસપાત્ર આરોગ્ય સાથી.",
    services: "સેવાઓ",
    quickLinks: "ઝડપી લિંક્સ",
    findHospitals: "હોસ્પિટલો શોધો",
    ourDoctors: "અમારા ડોક્ટરો",
    aboutUs: "અમારા વિશે",
    contact: "સંપર્ક",
    allRightsReserved: "બધા હકો અનામત.",
    offlineAvailable: "ઓફલાઇન ઉપલબ્ધ",
    lowDataMode: "ઓછો ડેટા મોડ",
    voiceSupport: "વોઇસ સપોર્ટ",
    tollFreeNumber: "ટોલ ફ્રી: 1800-XXX-XXXX",
    emergencyHelpline: "કટોકટી હેલ્પલાઇન",
    callNow: "હમણાં કૉલ કરો",
    smsService: "SMS સેવા",
    sendSMS: "SMS મોકલો",
    nearestCenter: "નજીકનું આરોગ્ય કેન્દ્ર",
    kmAway: "કિમી દૂર",
    ruralHealthFeatures: "ગ્રામીણ આરોગ્ય સુવિધાઓ",
    ruralDescription: "મર્યાદિત કનેક્ટિવિટી ધરાવતા ગ્રામીણ સમુદાયો માટે ખાસ સુવિધાઓ.",
    teleconsultation: "ટેલીકન્સલ્ટેશન",
    teleconsultDesc: "વિડિયો અથવા વોઇસ કૉલ દ્વારા ડોક્ટરો સાથે જોડાઓ",
    healthWorkerConnect: "આરોગ્ય કાર્યકર સંપર્ક",
    healthWorkerDesc: "તમારા વિસ્તારમાં આશા કાર્યકરો સાથે જોડાઓ",
    mobileClinic: "મોબાઇલ ક્લિનિક",
    mobileClinicDesc: "તમારા ગામમાં મોબાઇલ ક્લિનિક શેડ્યુલ જુઓ",
    medicineDroneDelivery: "ડ્રોન દવા ડિલિવરી",
    droneDeliveryDesc: "દૂરના વિસ્તારોમાં ડ્રોન દ્વારા દવાઓ મેળવો",
    symptomChecker: "AI લક્ષણ તપાસનાર",
    symptomCheckerDesc: "તમારા લક્ષણો વર્ણવો અને AI-સંચાલિત આરોગ્ય માહિતી મેળવો",
    selectSymptoms: "તમારા લક્ષણો પસંદ કરો",
    selectedSymptoms: "પસંદ કરેલા લક્ષણો",
    analyzeSymptoms: "લક્ષણોનું વિશ્લેષણ કરો",
    analyzing: "વિશ્લેષણ થઈ રહ્યું છે...",
    clearAll: "બધું સાફ કરો",
    analysisResults: "વિશ્લેષણ પરિણામો",
    possibleConditions: "સંભવિત સ્થિતિઓ",
    confidence: "વિશ્વાસ",
    severity: "તીવ્રતા",
    recommendations: "ભલામણો",
    consultDoctor: "ડોક્ટરની સલાહ લો",
    bookNow: "હમણાં બુક કરો",
    disclaimer: "અસ્વીકરણ",
    disclaimerText: "આ AI વિશ્લેષણ ફક્ત માહિતી માટે છે અને વ્યાવસાયિક તબીબી સલાહની જગ્યા લેતું નથી. ચોક્કસ નિદાન માટે કૃપા કરીને ડોક્ટરની સલાહ લો.",
    search: "શોધો",
    filter: "ફિલ્ટર",
    apply: "લાગુ કરો",
    cancel: "રદ કરો",
    confirm: "પુષ્ટિ કરો",
    back: "પાછળ",
    next: "આગળ",
    loading: "લોડ થઈ રહ્યું છે...",
    noResults: "કોઈ પરિણામો મળ્યા નથી",
    viewAll: "બધું જુઓ",
    learnMore: "વધુ જાણો",
    getStarted: "શરૂ કરો",
    selectDepartment: "વિભાગ પસંદ કરો",
    selectDoctor: "ડોક્ટર પસંદ કરો",
    selectDateTime: "તારીખ અને સમય પસંદ કરો",
    confirmBooking: "બુકિંગની પુષ્ટિ કરો",
    appointmentBooked: "એપોઇન્ટમેન્ટ બુક થઈ",
    appointmentDetails: "એપોઇન્ટમેન્ટ વિગતો",
    requestAmbulance: "એમ્બ્યુલન્સની વિનંતી કરો",
    emergencyType: "કટોકટીનો પ્રકાર",
    location: "સ્થાન",
    patientDetails: "દર્દીની વિગતો",
    trackAmbulance: "એમ્બ્યુલન્સ ટ્રેક કરો",
    eta: "પહોંચવાનો સમય",
    driverContact: "ડ્રાઇવર સંપર્ક",
    searchHospitals: "હોસ્પિટલો શોધો",
    bedsAvailable: "બેડ ઉપલબ્ધ",
    icuBeds: "ICU બેડ",
    emergencyServices: "કટોકટી સેવાઓ",
    departments: "વિભાગો",
    searchDoctors: "ડોક્ટરો શોધો",
    specialization: "વિશેષતા",
    experience: "અનુભવ",
    consultationFee: "પરામર્શ ફી",
    rating: "રેટિંગ",
    searchMedicine: "દવા શોધો",
    pharmacyNearYou: "તમારી નજીક ફાર્મસી",
    medicineAvailable: "દવા ઉપલબ્ધ",
    delivery: "ડિલિવરી",
    openNow: "હમણાં ખુલ્લું",
    lightMode: "લાઇટ મોડ",
    darkMode: "ડાર્ક મોડ",
    systemTheme: "સિસ્ટમ",
    selectLanguage: "ભાષા પસંદ કરો",
    language: "ભાષા",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("medicare-language") as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("medicare-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

